# name: datascience_py39
channels:
  - conda-forge
  - defaults
dependencies:
  - boto3
  - jupyter
  - numpy
  - pandas=1.4
  - scikit-learn=1.1
  - seaborn
  - statsmodels
  - xgboost
  - matplotlib
  - lightgbm
  - shap
  - scikit-optimize
  - sshtunnel
